### PR TITLE
montreal: remove legal session from day 1

### PR DESCRIPTION
**Pull request by MylesBorins**
Unfortunately max isn't able to make it after all

Apologies

### CODE REVIEW

**Comment by tieguy** [comment]
I'm available until 2:30 if this session could swap with the Collection and Social Media session?

(I'm the author of MPL 2.0, former attorney for Mozilla, Wikipedia, a variety of others.)

**Comment by WaleedAshraf** [comment]
we moved this session to Day 1, at 11:30 am in room Room 512DH. @tieguy will be leading the session. I have updated the agenda.
closing this pr.

**Comment by addaleax** [comment]
@WaleedAshraf That is about an hour in the past?

**Comment by WaleedAshraf** [comment]
yes, we moved it about 2 hours ago. I just saw this PR now.

**Pull request closed without merging**
